# Generated by Django 3.1.13 on 2023-04-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarPark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_park_no', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('x_coord', models.DecimalField(decimal_places=20, max_digits=40)),
                ('y_coord', models.DecimalField(decimal_places=20, max_digits=40)),
                ('free_parking', models.CharField(max_length=10)),
            ],
        ),
    ]
